#!/usr/bin/env sh
# vim: set filetype=sh tabstop=2 shiftwidth=2 expandtab :
# shellcheck shell=sh
set -o nounset -o errexit

export ARG0="$0"
export ARG0BASE="${0##*/}"
PROJECT_DIR="${0%/*}"
if test -z "$PROJECT_DIR"
then
  PROJECT_DIR="$PWD"
fi
export PROJECT_DIR
TASKS_DIR=
if test -r "$PROJECT_DIR"/"$ARG0BASE".sh
then
  TASKS_DIR="$PROJECT_DIR"
elif test -r "$PROJECT_DIR"/tasks/"$ARG0BASE".sh
then
  TASKS_DIR="$PROJECT_DIR"/tasks
fi
if test -z "$TASKS_DIR"
then
  echo "Cannot find script file for $ARG0" >&2
  exit 1
fi
export TASKS_DIR
script_file_path="$TASKS_DIR"/"$ARG0BASE".sh
for SH in /bin/dash /bin/ash /bin/bash
do
  # Avoid using Dash on Debian because which is built with --disable-lineno option.
  if test "$SH" = /bin/dash && test -e /etc/debian_version
  then
    continue
  fi
  # Avoid using Bash on macOS because which is locked to version 3.* and buggy.
  if test "$SH" = "/bin/bash" && test -e /System/Library/CoreServices/SystemVersion.plist
  then
    continue
  fi
  if test -x "$SH"
  then
    export SH
    exec "$SH" "$script_file_path" "$@"
  fi
done
echo "No appropriate shell found." >&2
exit 1
