#!/bin/bash
script_dir_path=$(dirname "${BASH_SOURCE[0]}")
script_name=$(basename "${BASH_SOURCE[0]}")
sh_dir_path="$script_dir_path"
env_file_path="$script_dir_path"/.env.sh
if test -r "$env_file_path"
then
  # shellcheck disable=SC1090
  . "$env_file_path"
fi
exec sh "$sh_dir_path/$script_name.sh" "$@"
