#!/usr/bin/env sh
# vim: set filetype=sh tabstop=2 shiftwidth=2 expandtab :
# shellcheck shell=sh
"${sourced_7a5b8a5-false}" && return 0; sourced_7a5b8a5=true

set -- "$PWD" "${0%/*}" "$@"; if test "$2" != "$0"; then cd "$2" 2>/dev/null || :; fi
. ./bar.lib.sh
cd "$1" || exit 1; shift 2

bar
