// This file is automatically generated by build.rs. DO NOT EDIT.

use std::collections::HashMap;

type RunFn = fn(&clap::ArgMatches) -> Result<(), Box<dyn std::error::Error>>;

mod fs;
mod hello;

pub fn init() -> (clap::Command, HashMap<String, RunFn>) {
    let mut cmd = clap::Command::new("");
    let mut hash = HashMap::new();

    cmd = foo::register(cmd);
    hash.insert("rsfoo".to_owned(), foo::run as RunFn);
    // cmd = fs::register(cmd);
    // hash.insert("fs".to_owned(), fs::run as RunFn);
    cmd = hello::register(cmd);
    hash.insert("rshello".to_owned(), hello::run as RunFn);

    (cmd, hash)
}
