// Code generated by build.rs; DO NOT EDIT.

mod subcmd_hello;
mod subcmd_list;

fn register_subcommands(main_command: &mut MainCommand) {
    main_command.register_subcommand(subcmd_hello::meta(), subcmd_hello::handler);
    main_command.register_subcommand(subcmd_list::meta(), subcmd_list::handler);
}
