// Code generated by build.rs; DO NOT EDIT.

mod subcmd_hello;

fn register_subcommands(main_command: &mut MainCommand) {
    main_command.register_subcommand(subcmd_hello::meta(), subcmd_hello::handler);
}
